name: Build Grit Engine

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Install Visual Studio 2017
    - name: Setup MSBuild and Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '15.0' # Visual Studio 2017

    # Install DirectX9 SDK
    - name: Install DirectX9 SDK
      run: |
        $url = "https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe"
        $output = "$env:TEMP\DXSDK_Jun10.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath $output -ArgumentList "/quiet" -Wait
        $env:DXSDK_DIR = "C:\Program Files (x86)\Microsoft DirectX SDK (June 2010)"
        [System.Environment]::SetEnvironmentVariable("DXSDK_DIR", $env:DXSDK_DIR, [System.EnvironmentVariableTarget]::Process)

    # Build the solution with Normal configuration
    - name: Build Grit Engine
      run: |
        msbuild grit-engine.sln /p:Configuration=Normal /p:Platform="Win32" /m

    # Commit build artifacts to master branch
    - name: Commit build changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Automated build and commit by GitHub Actions" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
