name: Build Grit Engine

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the Git repository with submodules
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Install dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion g++ make pkg-config gdb valgrind \
        libfreeimage-dev libzzip-dev libfreetype6-dev libglu1-mesa-dev \
        libxt-dev libxaw7-dev libglew-dev libxrandr-dev \
        libgoogle-perftools-dev libopenal-dev libreadline-dev freeglut3-dev \
        nvidia-cg-toolkit libvorbis-dev xutils-dev libicu-dev

    # Checkout SVN media directory
    - name: Checkout SVN media directory
      run: |
        svn checkout https://svn.code.sf.net/p/gritengine/code/trunk media

    # Build the project
    - name: Build Grit Engine
      run: |
        make -j $(nproc)

    # Commit build artifacts to master branch
    - name: Commit build changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Automated build and commit by GitHub Actions" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
