name: Build Grit Engine

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the Git repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Install SVN client
    - name: Install SVN
      run: |
        choco install svn --yes
    # Checkout SVN media directory
    - name: Checkout SVN media directory
      run: |
        svn checkout https://svn.code.sf.net/p/gritengine/code/trunk media
    # Install Visual Studio 2017
    - name: Setup MSBuild and Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '15.0' # Visual Studio 2017

    # Set DXSDK_DIR
    - name: Set DXSDK_DIR
      run: |
        echo "DXSDK_DIR=$HOME\cache\" >> $env:GITHUB_ENV

    # Cache DXSDK
    - name: Cache DXSDK
      id: cache-dxsdk
      uses: actions/cache@v4
      with:
        path: ~\cache
        key: dxsdk-jun10

    # Extract DirectX SDK if cache miss
    - name: Extract DirectX SDK
      if: steps.cache-dxsdk.outputs.cache-hit != 'true'
      run: |
        $url = "https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe"
        $exe = "_DX2010_.exe"
        Invoke-WebRequest -Uri $url -OutFile $exe
        7z x $exe DXSDK/Include -o_DX2010_
        7z x $exe DXSDK/Lib/x86 -o_DX2010_
        Move-Item .\_DX2010_\DXSDK $HOME\cache
        Remove-Item -Recurse -Force _DX*_ , $exe

    # Build the solution with Normal configuration
    - name: Build Grit Engine
      run: |
        msbuild grit-engine.sln /p:Configuration=Normal /p:Platform="Win32" /m
    # Commit build artifacts to master branch
    - name: Commit build changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Automated build and commit by GitHub Actions" || echo "No changes to commit"
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
